# Generated by Django 3.2.9 on 2021-12-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description_short', models.TextField(verbose_name='Короткое описание')),
                ('description_long', models.TextField(verbose_name='Полное описание')),
                ('lng', models.DecimalField(decimal_places=14, max_digits=17, verbose_name='Широта')),
                ('lan', models.DecimalField(decimal_places=14, max_digits=17, verbose_name='Долгота')),
            ],
        ),
    ]
