# Generated by Django 3.2.9 on 2021-12-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='lan',
            new_name='lat',
        ),
    ]
