# Generated by Django 3.2.9 on 2021-12-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_image_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='placeId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID места'),
        ),
    ]
