# Generated by Django 3.2.9 on 2022-01-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_alter_image_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='number',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Картинка'),
        ),
    ]
